version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: monthly
      time: "00:00"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      time: "00:00"
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: monthly
      time: "00:00"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: monthly
      time: "00:00"
