"""Add batch locking

Revision ID: 90db4a933a16
Revises: 9a098a265cbd
Create Date: 2024-01-18 14:21:22.487177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90db4a933a16"
down_revision: Union[str, None] = "9a098a265cbd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "batches", sa.Column("locked", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(op.f("ix_batches_locked"), "batches", ["locked"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_batches_locked"), table_name="batches")
    op.drop_column("batches", "locked")
    # ### end Alembic commands ###
