"""Initial revision

Revision ID: 930b75030da8
Revises: 
Create Date: 2024-01-01 21:20:15.639529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "930b75030da8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batch_jobs",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("batch_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("job_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["batches.id"], name="batch_jobs_batch_id_fkey"
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name="batch_jobs_job_id_fkey"),
        sa.PrimaryKeyConstraint("id", "batch_id", "job_id", name="batch_jobs_pkey"),
    )
    op.create_table(
        "batches",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('batches_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="batches_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_batches_created_at", "batches", ["created_at"], unique=False)
    op.create_table(
        "urls",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('urls_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("url", sa.VARCHAR(length=10000), autoincrement=False, nullable=False),
        sa.Column(
            "first_seen",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_seen",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="urls_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_urls_url", "urls", ["url"], unique=True)
    op.create_index("ix_urls_last_seen", "urls", ["last_seen"], unique=False)
    op.create_index("ix_urls_first_seen", "urls", ["first_seen"], unique=False)
    op.create_table(
        "repeat_urls",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("url_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("batch_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("interval", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "active_since",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["batch_id"], ["batches.id"], name="repeat_urls_batch_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["url_id"], ["urls.id"], name="repeat_urls_url_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="repeat_urls_pkey"),
        sa.UniqueConstraint("batch_id", name="repeat_urls_batch_id_key"),
        sa.UniqueConstraint("url_id", name="repeat_urls_url_id_key"),
    )
    op.create_index(
        "ix_repeat_urls_created_at", "repeat_urls", ["created_at"], unique=False
    )
    op.create_index(
        "ix_repeat_urls_active_since", "repeat_urls", ["active_since"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("url_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "completed",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "delayed_until",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("priority", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("retry", sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.Column(
            "failed",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["url_id"], ["urls.id"], name="jobs_url_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="jobs_pkey"),
    )
    op.create_index("ix_jobs_failed", "jobs", ["failed"], unique=False)
    op.create_index("ix_jobs_delayed_until", "jobs", ["delayed_until"], unique=False)
    op.create_index("ix_jobs_created_at", "jobs", ["created_at"], unique=False)
    op.create_index("ix_jobs_completed", "jobs", ["completed"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_jobs_completed", table_name="jobs")
    op.drop_index("ix_jobs_created_at", table_name="jobs")
    op.drop_index("ix_jobs_delayed_until", table_name="jobs")
    op.drop_index("ix_jobs_failed", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index("ix_repeat_urls_active_since", table_name="repeat_urls")
    op.drop_index("ix_repeat_urls_created_at", table_name="repeat_urls")
    op.drop_table("repeat_urls")
    op.drop_index("ix_urls_first_seen", table_name="urls")
    op.drop_index("ix_urls_last_seen", table_name="urls")
    op.drop_index("ix_urls_url", table_name="urls")
    op.drop_table("urls")
    op.drop_index("ix_batches_created_at", table_name="batches")
    op.drop_table("batches")
    op.drop_table("batch_jobs")
    # ### end Alembic commands ###
