"""Add a unique constraint

Revision ID: d53a99000a08
Revises: b3a25a74012d
Create Date: 2024-01-01 21:35:43.032412

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d53a99000a08"
down_revision: Union[str, None] = "b3a25a74012d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("_batch_job_uc", "batch_jobs", ["batch_id", "job_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_batch_job_uc", "batch_jobs", type_="unique")
    # ### end Alembic commands ###
