"""Fix pkey issue

Revision ID: f79ac07ca876
Revises: d53a99000a08
Create Date: 2024-01-01 21:36:52.346022

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f79ac07ca876"
down_revision: Union[str, None] = "d53a99000a08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("batch_jobs_pkey", "batch_jobs", type_="primary")
    op.create_primary_key("batch_jobs_pkey", "batch_jobs", ["id"], schema="public")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("batch_jobs_pkey", "batch_jobs", type_="primary")
    op.create_primary_key(
        "batch_jobs_pkey", "batch_jobs", ["id", "batch_id", "job_id"], schema="public"
    )
    pass
    # ### end Alembic commands ###
